-- ══════════════════════════════════════════════════
-- UPDATE descriptive names for all 5cm/5x33cm stickers
-- ══════════════════════════════════════════════════

UPDATE products SET name = 'Akrapovic Exhaust System',     name_bg = 'Akrapovic Exhaust System'     WHERE slug IN ('5cm-0','5cm-00','5cm-06');
UPDATE products SET name = 'Черепи с Лога на Марки',       name_bg = 'Черепи с Лога на Марки'       WHERE slug = '5cm-01';
UPDATE products SET name = 'Черепи Мулти-Бранд Колекция',  name_bg = 'Черепи Мулти-Бранд Колекция'  WHERE slug = '5cm-02';
UPDATE products SET name = '4x4 Off Road',                  name_bg = '4x4 Off Road'                  WHERE slug IN ('5cm-03');
UPDATE products SET name = 'Performance Limited Edition',   name_bg = 'Performance Limited Edition'   WHERE slug IN ('5cm-04','5cm-37');
UPDATE products SET name = 'Рейсинг Марки Колекция',       name_bg = 'Рейсинг Марки Колекция'       WHERE slug = '5cm-05';
UPDATE products SET name = 'ST Line — Ford Performance',   name_bg = 'ST Line — Ford Performance'   WHERE slug = '5cm-06';
UPDATE products SET name = 'Мото Рейсинг Стикери',         name_bg = 'Мото Рейсинг Стикери'         WHERE slug = '5cm-07';
UPDATE products SET name = 'Sports Mind — Powered by Brand', name_bg = 'Sports Mind — Powered by Brand' WHERE slug = '5cm-08';
UPDATE products SET name = 'BG Табела ЕС',                 name_bg = 'BG Табела ЕС'                 WHERE slug IN ('5cm-09','5cm-91');
UPDATE products SET name = 'VW Logo — Кръгли (6 бр.)',    name_bg = 'VW Logo — Кръгли (6 бр.)'    WHERE slug = '5cm-1';
UPDATE products SET name = 'Bulgaria Flag — Текст',        name_bg = 'Bulgaria Flag — Текст'        WHERE slug = '5cm-11';
UPDATE products SET name = 'Bulgaria Flag — Правоъгълен',  name_bg = 'Bulgaria Flag — Правоъгълен'  WHERE slug = '5cm-12';
UPDATE products SET name = 'DRAG — BMW M Цветове',         name_bg = 'DRAG — BMW M Цветове'         WHERE slug = '5cm-13';
UPDATE products SET name = 'Rolling Stones Hot Lips',       name_bg = 'Rolling Stones Hot Lips'       WHERE slug = '5cm-15';
UPDATE products SET name = 'BMW Logo — Кръгли (6 бр.)',   name_bg = 'BMW Logo — Кръгли (6 бр.)'   WHERE slug = '5cm-16';
UPDATE products SET name = 'Mercedes Logo — Кръгли (6 бр.)', name_bg = 'Mercedes Logo — Кръгли (6 бр.)' WHERE slug = '5cm-17';
UPDATE products SET name = 'Внимание — Автоматична Врата', name_bg = 'Внимание — Автоматична Врата' WHERE slug = '5cm-18';
UPDATE products SET name = 'BG/EU Флаг Стикери',           name_bg = 'BG/EU Флаг Стикери'           WHERE slug = '5cm-19';
UPDATE products SET name = 'BMW M Ленти',                   name_bg = 'BMW M Ленти'                   WHERE slug = '5cm-20';
UPDATE products SET name = 'Fake Taxi',                     name_bg = 'Fake Taxi'                     WHERE slug = '5cm-21';
UPDATE products SET name = 'Fresh / Dope as F*ck',         name_bg = 'Fresh / Dope as F*ck'         WHERE slug = '5cm-22';
UPDATE products SET name = 'Honda / Suzuki Loga',          name_bg = 'Honda / Suzuki Лога'           WHERE slug = '5cm-23';
UPDATE products SET name = 'I Love Haters',                 name_bg = 'I Love Haters'                 WHERE slug = '5cm-24';
UPDATE products SET name = 'I Love My Car',                 name_bg = 'I Love My Car'                 WHERE slug = '5cm-25';
UPDATE products SET name = 'JOM Power',                     name_bg = 'JOM Power'                     WHERE slug = '5cm-26';
UPDATE products SET name = 'Kawasaki Logo',                 name_bg = 'Kawasaki Logo'                 WHERE slug = '5cm-27';
UPDATE products SET name = 'KTM Logo',                      name_bg = 'KTM Logo'                      WHERE slug = '5cm-28';
UPDATE products SET name = 'KTM Ready for Race',            name_bg = 'KTM Ready for Race'            WHERE slug = '5cm-29';
UPDATE products SET name = 'Monster Energy — Вертикални',  name_bg = 'Monster Energy — Вертикални'  WHERE slug = '5cm-3';
UPDATE products SET name = 'Червен и Син Кръст',           name_bg = 'Червен и Син Кръст'           WHERE slug = '5cm-30';
UPDATE products SET name = 'Limited Edition — Скрипт',     name_bg = 'Limited Edition — Скрипт'     WHERE slug = '5cm-31';
UPDATE products SET name = 'Made in Japan — Rising Sun',   name_bg = 'Made in Japan — Rising Sun'   WHERE slug = '5cm-32';
UPDATE products SET name = 'Madness Motorsports',           name_bg = 'Madness Motorsports'           WHERE slug = '5cm-33';
UPDATE products SET name = 'Monster Energy Brand',          name_bg = 'Monster Energy Brand'          WHERE slug = '5cm-34';
UPDATE products SET name = 'Monster Energy — Кръгли (4 бр.)', name_bg = 'Monster Energy — Кръгли (4 бр.)' WHERE slug = '5cm-35';
UPDATE products SET name = 'Monster Energy — Кръгли Сет',  name_bg = 'Monster Energy — Кръгли Сет'  WHERE slug = '5cm-36';
UPDATE products SET name = 'Performance Ltd. Ed. Multicolor', name_bg = 'Performance Ltd. Ed. Multicolor' WHERE slug = '5cm-41';
UPDATE products SET name = 'M Power — BMW Logo',           name_bg = 'M Power — BMW Logo'           WHERE slug = '5cm-38';
UPDATE products SET name = 'Powered by BMW Motorsport',    name_bg = 'Powered by BMW Motorsport'    WHERE slug = '5cm-39';
UPDATE products SET name = 'Пламъци — Червено/Оранжево',  name_bg = 'Пламъци — Червено/Оранжево'  WHERE slug IN ('5cm-4','5cm-45');
UPDATE products SET name = 'No Smoking Sign',               name_bg = 'Забранено Пушенето'           WHERE slug = '5cm-40';
UPDATE products SET name = 'Rock Shox PIKE / Yeti MTB',   name_bg = 'Rock Shox PIKE / Yeti MTB'   WHERE slug IN ('5cm-43','5cm-44');
UPDATE products SET name = 'Бик с Пламъци',                name_bg = 'Бик с Пламъци'                WHERE slug IN ('5cm-46','5cm-47');
UPDATE products SET name = 'Rock Shox Logo',               name_bg = 'Rock Shox Logo'               WHERE slug IN ('5cm-49','5cm-5','5cm-50','5cm-51');
UPDATE products SET name = 'RS Logo — Голям',             name_bg = 'RS Logo — Голям'             WHERE slug = '5cm-52';
UPDATE products SET name = 'RS Logo — Малък',             name_bg = 'RS Logo — Малък'             WHERE slug = '5cm-53';
UPDATE products SET name = 'Specialized Bikes Logo',       name_bg = 'Specialized Bikes Logo'       WHERE slug = '5cm-54';
UPDATE products SET name = 'Sprinter — Mercedes',          name_bg = 'Sprinter — Mercedes'          WHERE slug = '5cm-55';
UPDATE products SET name = 'SR Suntour XCT Вилки',        name_bg = 'SR Suntour XCT Вилки'        WHERE slug = '5cm-57';
UPDATE products SET name = 'Static — Пружина',             name_bg = 'Static — Пружина'             WHERE slug = '5cm-58';
UPDATE products SET name = 'Street Racing — Powered by Audi', name_bg = 'Street Racing — Powered by Audi' WHERE slug = '5cm-59';
UPDATE products SET name = 'Yamaha Logo — Черен',          name_bg = 'Yamaha Logo — Черен'          WHERE slug IN ('5cm-6','5cm-69');
UPDATE products SET name = 'Street Racing — Powered by BMW', name_bg = 'Street Racing — Powered by BMW' WHERE slug = '5cm-60';
UPDATE products SET name = 'Street Racing — Powered by Opel', name_bg = 'Street Racing — Powered by Opel' WHERE slug = '5cm-61';
UPDATE products SET name = 'Street Racing — Powered by VW', name_bg = 'Street Racing — Powered by VW' WHERE slug = '5cm-62';
UPDATE products SET name = 'TMAX — Yamaha Скутер',         name_bg = 'TMAX — Yamaha Скутер'         WHERE slug = '5cm-63';
UPDATE products SET name = 'Transit — Ford',               name_bg = 'Transit — Ford'               WHERE slug = '5cm-64';
UPDATE products SET name = 'Transporter — VW',             name_bg = 'Transporter — VW'             WHERE slug = '5cm-65';
UPDATE products SET name = 'Trek Bikes Logo',              name_bg = 'Trek Bikes Logo'              WHERE slug = '5cm-67';
UPDATE products SET name = 'Yamaha Logo — Син',            name_bg = 'Yamaha Logo — Син'            WHERE slug = '5cm-70';
UPDATE products SET name = '1,4 е Моторчето на Чистачките', name_bg = '1,4 е Моторчето на Чистачките' WHERE slug = '5cm-71';
UPDATE products SET name = 'Bulgaria — Трибагреник',       name_bg = 'Bulgaria — Трибагреник'       WHERE slug = '5cm-72';
UPDATE products SET name = 'VWClub.bg Logo',               name_bg = 'VWClub.bg Logo'               WHERE slug = '5cm-73';
UPDATE products SET name = 'Fox Racing Logo',              name_bg = 'Fox Racing Logo'              WHERE slug = '5cm-74';
UPDATE products SET name = 'Fox Racing — Колекция',        name_bg = 'Fox Racing — Колекция'        WHERE slug IN ('5cm-75','5cm-82');
UPDATE products SET name = 'Monster Energy + Fox Комбо',   name_bg = 'Monster Energy + Fox Комбо'   WHERE slug = '5cm-76';
UPDATE products SET name = 'Renault F1 Team',              name_bg = 'Renault F1 Team'              WHERE slug = '5cm-77';
UPDATE products SET name = 'Alpinestars Star Logo',        name_bg = 'Alpinestars Star Logo'        WHERE slug = '5cm-78';
UPDATE products SET name = 'KYB Амортисьори',              name_bg = 'KYB Амортисьори'              WHERE slug = '5cm-79';
UPDATE products SET name = 'Visa / Mastercard / Maestro',  name_bg = 'Visa / Mastercard / Maestro'  WHERE slug = '5cm-80';
UPDATE products SET name = 'SB Shockblaze MTB Logo',       name_bg = 'SB Shockblaze MTB Logo'       WHERE slug = '5cm-81';
UPDATE products SET name = 'Pin-up Girl — Кестенява',      name_bg = 'Pin-up Girl — Кестенява'      WHERE slug = '5cm-83';
UPDATE products SET name = 'Pin-up Girl — Блондинка',      name_bg = 'Pin-up Girl — Блондинка'      WHERE slug = '5cm-84';
UPDATE products SET name = 'Pin-up Girl — Гръб',           name_bg = 'Pin-up Girl — Гръб'           WHERE slug = '5cm-85';
UPDATE products SET name = 'Безалкохолно Ме Черпят',       name_bg = 'Безалкохолно Ме Черпят'       WHERE slug = '5cm-86';
UPDATE products SET name = 'Карам с Жълта Книжка',         name_bg = 'Карам с Жълта Книжка'         WHERE slug = '5cm-87';
UPDATE products SET name = 'Ръждата е По-лека от Карбона', name_bg = 'Ръждата е По-лека от Карбона' WHERE slug = '5cm-88';
UPDATE products SET name = 'На Жени и Спирачки Не Вярвам', name_bg = 'На Жени и Спирачки Не Вярвам' WHERE slug = '5cm-89';
UPDATE products SET name = '100% Electric',                 name_bg = '100% Electric'                 WHERE slug = '5cm-90';
UPDATE products SET name = 'Brazzers Logo',                name_bg = 'Brazzers Logo'                WHERE slug IN ('5cm-92','5cm-93');
UPDATE products SET name = 'Game Over — Череп',            name_bg = 'Game Over — Череп'            WHERE slug = '5cm-94';

-- 5x33cm banners
UPDATE products SET name = 'S-line — Audi Motorsport',    name_bg = 'S-line — Audi Motorsport'    WHERE slug IN ('5x33cm-00','5x33cm-09');
UPDATE products SET name = 'Dunlop Гуми',                  name_bg = 'Dunlop Гуми'                  WHERE slug IN ('5x33cm-01','5x33cm-14');
UPDATE products SET name = '4x4 Off Road — Банер',         name_bg = '4x4 Off Road — Банер'         WHERE slug IN ('5x33cm-04','5x33-04');
UPDATE products SET name = 'Sprinter — Банер',             name_bg = 'Sprinter — Банер'             WHERE slug IN ('5x33cm-05','5x33cm-56');
UPDATE products SET name = 'VW Motorsport — Германско Знаме', name_bg = 'VW Motorsport — Германско Знаме' WHERE slug IN ('5x33cm-06','5x33cm-68');
UPDATE products SET name = 'Bridgestone Гуми',             name_bg = 'Bridgestone Гуми'             WHERE slug = '5x33cm-10';
UPDATE products SET name = 'BMW M Performance — Банер',    name_bg = 'BMW M Performance — Банер'    WHERE slug = '5x33cm-42';
UPDATE products SET name = 'Renthal — Мото/Вело',          name_bg = 'Renthal — Мото/Вело'          WHERE slug = '5x33cm-48';
UPDATE products SET name = 'Transporter — VW Банер',       name_bg = 'Transporter — VW Банер'       WHERE slug = '5x33cm-66';
