UPDATE products SET 
                name = '12CM-02',
                name_bg = '12CM-02',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379534/Site_Pics/Decals/12cm/12cm-02.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379534/Site_Pics/Decals/12cm/12cm-02.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-02';
UPDATE products SET 
                name = '12CM-03',
                name_bg = '12CM-03',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379535/Site_Pics/Decals/12cm/12cm-03.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379535/Site_Pics/Decals/12cm/12cm-03.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-03';
UPDATE products SET 
                name = '12CM-04',
                name_bg = '12CM-04',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379536/Site_Pics/Decals/12cm/12cm-04.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379536/Site_Pics/Decals/12cm/12cm-04.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-04';
UPDATE products SET 
                name = '12CM-05',
                name_bg = '12CM-05',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379538/Site_Pics/Decals/12cm/12cm-05.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379538/Site_Pics/Decals/12cm/12cm-05.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-05';
UPDATE products SET 
                name = '12CM-06',
                name_bg = '12CM-06',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379540/Site_Pics/Decals/12cm/12cm-06.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379540/Site_Pics/Decals/12cm/12cm-06.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-06';
UPDATE products SET 
                name = '12CM-07',
                name_bg = '12CM-07',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379541/Site_Pics/Decals/12cm/12cm-07.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379541/Site_Pics/Decals/12cm/12cm-07.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-07';
UPDATE products SET 
                name = '12CM-08',
                name_bg = '12CM-08',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379542/Site_Pics/Decals/12cm/12cm-08.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379542/Site_Pics/Decals/12cm/12cm-08.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-08';
UPDATE products SET 
                name = '12CM-09',
                name_bg = '12CM-09',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379543/Site_Pics/Decals/12cm/12cm-09.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379543/Site_Pics/Decals/12cm/12cm-09.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-09';
UPDATE products SET 
                name = '12CM-10',
                name_bg = '12CM-10',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379548/Site_Pics/Decals/12cm/12cm-10.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379548/Site_Pics/Decals/12cm/12cm-10.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-10';
UPDATE products SET 
                name = '12CM-11',
                name_bg = '12CM-11',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379559/Site_Pics/Decals/12cm/12cm-11.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379559/Site_Pics/Decals/12cm/12cm-11.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-11';
UPDATE products SET 
                name = '12CM-12',
                name_bg = '12CM-12',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379585/Site_Pics/Decals/12cm/12cm-12.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379585/Site_Pics/Decals/12cm/12cm-12.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-12';
UPDATE products SET 
                name = '12CM-13',
                name_bg = '12CM-13',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379623/Site_Pics/Decals/12cm/12cm-13.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379623/Site_Pics/Decals/12cm/12cm-13.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-13';
UPDATE products SET 
                name = '12CM-14',
                name_bg = '12CM-14',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379648/Site_Pics/Decals/12cm/12cm-14.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379648/Site_Pics/Decals/12cm/12cm-14.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-14';
UPDATE products SET 
                name = '12CM-15',
                name_bg = '12CM-15',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379668/Site_Pics/Decals/12cm/12cm-15.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379668/Site_Pics/Decals/12cm/12cm-15.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-15';
UPDATE products SET 
                name = '12CM-16',
                name_bg = '12CM-16',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379683/Site_Pics/Decals/12cm/12cm-16.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379683/Site_Pics/Decals/12cm/12cm-16.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-16';
UPDATE products SET 
                name = '12CM-17',
                name_bg = '12CM-17',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379700/Site_Pics/Decals/12cm/12cm-17.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379700/Site_Pics/Decals/12cm/12cm-17.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-17';
UPDATE products SET 
                name = '12CM-18',
                name_bg = '12CM-18',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-18.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-18.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-18';
UPDATE products SET 
                name = '12CM-19',
                name_bg = '12CM-19',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-19.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-19.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-19';
UPDATE products SET 
                name = '12CM-20',
                name_bg = '12CM-20',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379937/Site_Pics/Decals/12cm/12cm-20.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379937/Site_Pics/Decals/12cm/12cm-20.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-20';
UPDATE products SET 
                name = '12CM-21',
                name_bg = '12CM-21',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-21.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-21.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-21';
UPDATE products SET 
                name = '12CM-22',
                name_bg = '12CM-22',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-22.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-22.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-22';
UPDATE products SET 
                name = '12CM-23',
                name_bg = '12CM-23',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-23.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-23.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-23';
UPDATE products SET 
                name = '12CM-24',
                name_bg = '12CM-24',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379962/Site_Pics/Decals/12cm/12cm-24.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379962/Site_Pics/Decals/12cm/12cm-24.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-24';
UPDATE products SET 
                name = '12CM-25',
                name_bg = '12CM-25',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-25.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-25.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-25';
UPDATE products SET 
                name = '12CM-26',
                name_bg = '12CM-26',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-26.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-26.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-26';
UPDATE products SET 
                name = '12CM-27',
                name_bg = '12CM-27',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-27.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-27.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-27';
UPDATE products SET 
                name = '12CM-28',
                name_bg = '12CM-28',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380075/Site_Pics/Decals/12cm/12cm-28.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380075/Site_Pics/Decals/12cm/12cm-28.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-28';
UPDATE products SET 
                name = '12CM-29',
                name_bg = '12CM-29',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380093/Site_Pics/Decals/12cm/12cm-29.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380093/Site_Pics/Decals/12cm/12cm-29.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-29';
UPDATE products SET 
                name = '12CM-30',
                name_bg = '12CM-30',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380104/Site_Pics/Decals/12cm/12cm-30.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380104/Site_Pics/Decals/12cm/12cm-30.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-30';
UPDATE products SET 
                name = '12CM-31',
                name_bg = '12CM-31',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380108/Site_Pics/Decals/12cm/12cm-31.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380108/Site_Pics/Decals/12cm/12cm-31.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-31';
UPDATE products SET 
                name = '12CM-32',
                name_bg = '12CM-32',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-32.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-32.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-32';
UPDATE products SET 
                name = '12CM-33',
                name_bg = '12CM-33',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-33.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-33.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-33';
UPDATE products SET 
                name = '12CM-34',
                name_bg = '12CM-34',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-34.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-34.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-34';
UPDATE products SET 
                name = '12CM-35',
                name_bg = '12CM-35',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-35.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-35.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-35';
UPDATE products SET 
                name = '12CM-36',
                name_bg = '12CM-36',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-36.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-36.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-36';
UPDATE products SET 
                name = '12CM-37',
                name_bg = '12CM-37',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380196/Site_Pics/Decals/12cm/12cm-37.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380196/Site_Pics/Decals/12cm/12cm-37.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-37';
UPDATE products SET 
                name = '12CM-38',
                name_bg = '12CM-38',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-38.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-38.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-38';
UPDATE products SET 
                name = '12CM-39',
                name_bg = '12CM-39',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-39.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-39.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-39';
UPDATE products SET 
                name = '12CM-40',
                name_bg = '12CM-40',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-40.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-40.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-40';
UPDATE products SET 
                name = '12CM-41',
                name_bg = '12CM-41',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-41.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-41.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-41';
UPDATE products SET 
                name = '12CM-42',
                name_bg = '12CM-42',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-42.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-42.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-42';
UPDATE products SET 
                name = '12CM-43',
                name_bg = '12CM-43',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-43.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-43.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-43';
UPDATE products SET 
                name = '12CM-44',
                name_bg = '12CM-44',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-44.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-44.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-44';
UPDATE products SET 
                name = '12CM-45',
                name_bg = '12CM-45',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-45.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-45.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-45';
UPDATE products SET 
                name = '12CM-46',
                name_bg = '12CM-46',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-46.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-46.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-46';
UPDATE products SET 
                name = '12CM-47',
                name_bg = '12CM-47',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-47.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-47.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-47';
UPDATE products SET 
                name = '12CM-48',
                name_bg = '12CM-48',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-48.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-48.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-48';
UPDATE products SET 
                name = '12CM-49',
                name_bg = '12CM-49',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-49.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-49.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-49';
UPDATE products SET 
                name = '12CM-50',
                name_bg = '12CM-50',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-50.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380213/Site_Pics/Decals/12cm/12cm-50.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-50';
UPDATE products SET 
                name = '12CM-51',
                name_bg = '12CM-51',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-51.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-51.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-51';
UPDATE products SET 
                name = '12CM-52',
                name_bg = '12CM-52',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-52.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-52.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-52';
UPDATE products SET 
                name = '12CM-53',
                name_bg = '12CM-53',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-53.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-53.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-53';
UPDATE products SET 
                name = '12CM-54',
                name_bg = '12CM-54',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-54.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-54.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-54';
UPDATE products SET 
                name = '12CM-55',
                name_bg = '12CM-55',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-55.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-55.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-55';
UPDATE products SET 
                name = '12CM-56',
                name_bg = '12CM-56',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-56.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-56.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-56';
UPDATE products SET 
                name = '12CM-57',
                name_bg = '12CM-57',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-57.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-57.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-57';
UPDATE products SET 
                name = '12CM-58',
                name_bg = '12CM-58',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-58.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-58.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-58';
UPDATE products SET 
                name = '12CM-59',
                name_bg = '12CM-59',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-59.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-59.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-59';
UPDATE products SET 
                name = '12CM-60',
                name_bg = '12CM-60',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-60.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380214/Site_Pics/Decals/12cm/12cm-60.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-60';
UPDATE products SET 
                name = '12CM-61',
                name_bg = '12CM-61',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-61.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-61.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-61';
UPDATE products SET 
                name = '12CM-62',
                name_bg = '12CM-62',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-62.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-62.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-62';
UPDATE products SET 
                name = '12CM-63',
                name_bg = '12CM-63',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-63.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-63.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-63';
UPDATE products SET 
                name = '12CM-64',
                name_bg = '12CM-64',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-64.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-64.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-64';
UPDATE products SET 
                name = '12CM-65',
                name_bg = '12CM-65',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-65.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-65.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-65';
UPDATE products SET 
                name = '12CM-66',
                name_bg = '12CM-66',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-66.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-66.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-66';
UPDATE products SET 
                name = '12CM-67',
                name_bg = '12CM-67',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-67.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-67.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-67';
UPDATE products SET 
                name = '12CM-68',
                name_bg = '12CM-68',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-68.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-68.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-68';
UPDATE products SET 
                name = '12CM-69',
                name_bg = '12CM-69',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-69.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-69.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-69';
UPDATE products SET 
                name = '12CM-70',
                name_bg = '12CM-70',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-70.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380220/Site_Pics/Decals/12cm/12cm-70.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-70';
UPDATE products SET 
                name = '12CM-71',
                name_bg = '12CM-71',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380237/Site_Pics/Decals/12cm/12cm-71.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380237/Site_Pics/Decals/12cm/12cm-71.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-71';
UPDATE products SET 
                name = '12CM-72',
                name_bg = '12CM-72',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380232/Site_Pics/Decals/12cm/12cm-72.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380232/Site_Pics/Decals/12cm/12cm-72.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-72';
UPDATE products SET 
                name = '12CM-73',
                name_bg = '12CM-73',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380233/Site_Pics/Decals/12cm/12cm-73.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380233/Site_Pics/Decals/12cm/12cm-73.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-73';
UPDATE products SET 
                name = '12CM-74',
                name_bg = '12CM-74',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380237/Site_Pics/Decals/12cm/12cm-74.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380237/Site_Pics/Decals/12cm/12cm-74.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-74';
UPDATE products SET 
                name = '12CM-75',
                name_bg = '12CM-75',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380235/Site_Pics/Decals/12cm/12cm-75.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380235/Site_Pics/Decals/12cm/12cm-75.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-75';
UPDATE products SET 
                name = '12CM-76',
                name_bg = '12CM-76',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380237/Site_Pics/Decals/12cm/12cm-76.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380237/Site_Pics/Decals/12cm/12cm-76.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-76';
UPDATE products SET 
                name = '12CM-77',
                name_bg = '12CM-77',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380227/Site_Pics/Decals/12cm/12cm-77.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380227/Site_Pics/Decals/12cm/12cm-77.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-77';
UPDATE products SET 
                name = '12CM-78',
                name_bg = '12CM-78',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380227/Site_Pics/Decals/12cm/12cm-78.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380227/Site_Pics/Decals/12cm/12cm-78.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-78';
UPDATE products SET 
                name = '12CM-79',
                name_bg = '12CM-79',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380225/Site_Pics/Decals/12cm/12cm-79.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380225/Site_Pics/Decals/12cm/12cm-79.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-79';
UPDATE products SET 
                name = '12CM-80',
                name_bg = '12CM-80',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380239/Site_Pics/Decals/12cm/12cm-80.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380239/Site_Pics/Decals/12cm/12cm-80.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-80';
UPDATE products SET 
                name = '12CM-81',
                name_bg = '12CM-81',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-81.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-81.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-81';
UPDATE products SET 
                name = '12CM-82',
                name_bg = '12CM-82',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-82.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-82.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-82';
UPDATE products SET 
                name = '12CM-83',
                name_bg = '12CM-83',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-83.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-83.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-83';
UPDATE products SET 
                name = '12CM-84',
                name_bg = '12CM-84',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-84.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-84.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-84';
UPDATE products SET 
                name = '12CM-85',
                name_bg = '12CM-85',
                avatar = '/Site_Pics/Decals/12cm/12cm-85.jpg',
                cover_image = '/Site_Pics/Decals/12cm/12cm-85.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-85';
UPDATE products SET 
                name = '12CM-86',
                name_bg = '12CM-86',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-86.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-86.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-86';
UPDATE products SET 
                name = '12CM-87',
                name_bg = '12CM-87',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380243/Site_Pics/Decals/12cm/12cm-87.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380243/Site_Pics/Decals/12cm/12cm-87.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-87';
UPDATE products SET 
                name = '12CM-88',
                name_bg = '12CM-88',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-88.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380242/Site_Pics/Decals/12cm/12cm-88.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-88';
UPDATE products SET 
                name = '12CM-89',
                name_bg = '12CM-89',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380243/Site_Pics/Decals/12cm/12cm-89.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380243/Site_Pics/Decals/12cm/12cm-89.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-89';
UPDATE products SET 
                name = '12CM-90',
                name_bg = '12CM-90',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380243/Site_Pics/Decals/12cm/12cm-90.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380243/Site_Pics/Decals/12cm/12cm-90.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-90';
UPDATE products SET 
                name = '12CM-91',
                name_bg = '12CM-91',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-91.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-91.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-91';
UPDATE products SET 
                name = '12CM-92',
                name_bg = '12CM-92',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-92.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-92.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-92';
UPDATE products SET 
                name = '12CM-93',
                name_bg = '12CM-93',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-93.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-93.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-93';
UPDATE products SET 
                name = '12CM-94',
                name_bg = '12CM-94',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380244/Site_Pics/Decals/12cm/12cm-94.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380244/Site_Pics/Decals/12cm/12cm-94.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-94';
UPDATE products SET 
                name = '12CM-95',
                name_bg = '12CM-95',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380244/Site_Pics/Decals/12cm/12cm-95.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380244/Site_Pics/Decals/12cm/12cm-95.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-95';
UPDATE products SET 
                name = '12CM-96',
                name_bg = '12CM-96',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-96.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-96.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-96';
UPDATE products SET 
                name = '12CM-97',
                name_bg = '12CM-97',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-97.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-97.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-97';
UPDATE products SET 
                name = '12CM-98',
                name_bg = '12CM-98',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-98.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-98.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-98';
UPDATE products SET 
                name = '12CM-99',
                name_bg = '12CM-99',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-99.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380245/Site_Pics/Decals/12cm/12cm-99.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-99';
UPDATE products SET 
                name = '12CM-100',
                name_bg = '12CM-100',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379550/Site_Pics/Decals/12cm/12cm-100.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379550/Site_Pics/Decals/12cm/12cm-100.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-100';
UPDATE products SET 
                name = '12CM-101',
                name_bg = '12CM-101',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379551/Site_Pics/Decals/12cm/12cm-101.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379551/Site_Pics/Decals/12cm/12cm-101.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-101';
