UPDATE products SET 
                name = '12CM-202',
                name_bg = '12CM-202',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379935/Site_Pics/Decals/12cm/12cm-202.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379935/Site_Pics/Decals/12cm/12cm-202.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-202';
UPDATE products SET 
                name = '12CM-203',
                name_bg = '12CM-203',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379936/Site_Pics/Decals/12cm/12cm-203.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379936/Site_Pics/Decals/12cm/12cm-203.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-203';
UPDATE products SET 
                name = '12CM-204',
                name_bg = '12CM-204',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-204.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-204.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-204';
UPDATE products SET 
                name = '12CM-205',
                name_bg = '12CM-205',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-205.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-205.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-205';
UPDATE products SET 
                name = '12CM-206',
                name_bg = '12CM-206',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-206.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-206.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-206';
UPDATE products SET 
                name = '12CM-207',
                name_bg = '12CM-207',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-207.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-207.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-207';
UPDATE products SET 
                name = '12CM-208',
                name_bg = '12CM-208',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-208.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-208.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-208';
UPDATE products SET 
                name = '12CM-209',
                name_bg = '12CM-209',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-209.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-209.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-209';
UPDATE products SET 
                name = '12CM-210',
                name_bg = '12CM-210',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-210.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-210.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-210';
UPDATE products SET 
                name = '12CM-211',
                name_bg = '12CM-211',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-211.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-211.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-211';
UPDATE products SET 
                name = '12CM-212',
                name_bg = '12CM-212',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-212.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379940/Site_Pics/Decals/12cm/12cm-212.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-212';
UPDATE products SET 
                name = '12CM-213',
                name_bg = '12CM-213',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-213.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-213.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-213';
UPDATE products SET 
                name = '12CM-214',
                name_bg = '12CM-214',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-214.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-214.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-214';
UPDATE products SET 
                name = '12CM-215',
                name_bg = '12CM-215',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379950/Site_Pics/Decals/12cm/12cm-215.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379950/Site_Pics/Decals/12cm/12cm-215.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-215';
UPDATE products SET 
                name = '12CM-216',
                name_bg = '12CM-216',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-216.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-216.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-216';
UPDATE products SET 
                name = '12CM-217',
                name_bg = '12CM-217',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-217.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-217.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-217';
UPDATE products SET 
                name = '12CM-218',
                name_bg = '12CM-218',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-218.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-218.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-218';
UPDATE products SET 
                name = '12CM-219',
                name_bg = '12CM-219',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379950/Site_Pics/Decals/12cm/12cm-219.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379950/Site_Pics/Decals/12cm/12cm-219.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-219';
UPDATE products SET 
                name = '12CM-220',
                name_bg = '12CM-220',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379948/Site_Pics/Decals/12cm/12cm-220.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379948/Site_Pics/Decals/12cm/12cm-220.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-220';
UPDATE products SET 
                name = '12CM-221',
                name_bg = '12CM-221',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-221.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379947/Site_Pics/Decals/12cm/12cm-221.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-221';
UPDATE products SET 
                name = '12CM-222',
                name_bg = '12CM-222',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-222.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-222.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-222';
UPDATE products SET 
                name = '12CM-223',
                name_bg = '12CM-223',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379955/Site_Pics/Decals/12cm/12cm-223.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379955/Site_Pics/Decals/12cm/12cm-223.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-223';
UPDATE products SET 
                name = '12CM-224',
                name_bg = '12CM-224',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379959/Site_Pics/Decals/12cm/12cm-224.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379959/Site_Pics/Decals/12cm/12cm-224.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-224';
UPDATE products SET 
                name = '12CM-225',
                name_bg = '12CM-225',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379954/Site_Pics/Decals/12cm/12cm-225.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379954/Site_Pics/Decals/12cm/12cm-225.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-225';
UPDATE products SET 
                name = '12CM-226',
                name_bg = '12CM-226',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379954/Site_Pics/Decals/12cm/12cm-226.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379954/Site_Pics/Decals/12cm/12cm-226.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-226';
UPDATE products SET 
                name = '12CM-227',
                name_bg = '12CM-227',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-227.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-227.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-227';
UPDATE products SET 
                name = '12CM-228',
                name_bg = '12CM-228',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379958/Site_Pics/Decals/12cm/12cm-228.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379958/Site_Pics/Decals/12cm/12cm-228.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-228';
UPDATE products SET 
                name = '12CM-229',
                name_bg = '12CM-229',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379958/Site_Pics/Decals/12cm/12cm-229.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379958/Site_Pics/Decals/12cm/12cm-229.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-229';
UPDATE products SET 
                name = '12CM-230',
                name_bg = '12CM-230',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-230.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379952/Site_Pics/Decals/12cm/12cm-230.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-230';
UPDATE products SET 
                name = '12CM-231',
                name_bg = '12CM-231',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-231.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-231.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-231';
UPDATE products SET 
                name = '12CM-232',
                name_bg = '12CM-232',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-232.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-232.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-232';
UPDATE products SET 
                name = '12CM-233',
                name_bg = '12CM-233',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-233.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-233.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-233';
UPDATE products SET 
                name = '12CM-234',
                name_bg = '12CM-234',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-234.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-234.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-234';
UPDATE products SET 
                name = '12CM-235',
                name_bg = '12CM-235',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-235.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379960/Site_Pics/Decals/12cm/12cm-235.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-235';
UPDATE products SET 
                name = '12CM-236',
                name_bg = '12CM-236',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-236.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-236.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-236';
UPDATE products SET 
                name = '12CM-237',
                name_bg = '12CM-237',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-237.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-237.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-237';
UPDATE products SET 
                name = '12CM-238',
                name_bg = '12CM-238',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-238.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379961/Site_Pics/Decals/12cm/12cm-238.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-238';
UPDATE products SET 
                name = '12CM-239',
                name_bg = '12CM-239',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379962/Site_Pics/Decals/12cm/12cm-239.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379962/Site_Pics/Decals/12cm/12cm-239.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-239';
UPDATE products SET 
                name = '12CM-240',
                name_bg = '12CM-240',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-240.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-240.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-240';
UPDATE products SET 
                name = '12CM-241',
                name_bg = '12CM-241',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-241.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-241.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-241';
UPDATE products SET 
                name = '12CM-242',
                name_bg = '12CM-242',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-242.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-242.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-242';
UPDATE products SET 
                name = '12CM-243',
                name_bg = '12CM-243',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-243.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-243.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-243';
UPDATE products SET 
                name = '12CM-244',
                name_bg = '12CM-244',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-244.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-244.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-244';
UPDATE products SET 
                name = '12CM-245',
                name_bg = '12CM-245',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-245.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-245.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-245';
UPDATE products SET 
                name = '12CM-246',
                name_bg = '12CM-246',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-246.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-246.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-246';
UPDATE products SET 
                name = '12CM-247',
                name_bg = '12CM-247',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379964/Site_Pics/Decals/12cm/12cm-247.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379964/Site_Pics/Decals/12cm/12cm-247.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-247';
UPDATE products SET 
                name = '12CM-248',
                name_bg = '12CM-248',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-248.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-248.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-248';
UPDATE products SET 
                name = '12CM-249',
                name_bg = '12CM-249',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-249.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379963/Site_Pics/Decals/12cm/12cm-249.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-249';
UPDATE products SET 
                name = '12CM-250',
                name_bg = '12CM-250',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-250.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-250.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-250';
UPDATE products SET 
                name = '12CM-251',
                name_bg = '12CM-251',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-251.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-251.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-251';
UPDATE products SET 
                name = '12CM-252',
                name_bg = '12CM-252',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-252.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-252.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-252';
UPDATE products SET 
                name = '12CM-253',
                name_bg = '12CM-253',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-253.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-253.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-253';
UPDATE products SET 
                name = '12CM-254',
                name_bg = '12CM-254',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-254.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-254.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-254';
UPDATE products SET 
                name = '12CM-255',
                name_bg = '12CM-255',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-255.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-255.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-255';
UPDATE products SET 
                name = '12CM-256',
                name_bg = '12CM-256',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-256.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-256.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-256';
UPDATE products SET 
                name = '12CM-257',
                name_bg = '12CM-257',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-257.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-257.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-257';
UPDATE products SET 
                name = '12CM-258',
                name_bg = '12CM-258',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-258.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379965/Site_Pics/Decals/12cm/12cm-258.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-258';
UPDATE products SET 
                name = '12CM-259',
                name_bg = '12CM-259',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-259.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-259.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-259';
UPDATE products SET 
                name = '12CM-260',
                name_bg = '12CM-260',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-260.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-260.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-260';
UPDATE products SET 
                name = '12CM-261',
                name_bg = '12CM-261',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-261.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-261.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-261';
UPDATE products SET 
                name = '12CM-262',
                name_bg = '12CM-262',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-262.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-262.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-262';
UPDATE products SET 
                name = '12CM-263',
                name_bg = '12CM-263',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-263.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-263.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-263';
UPDATE products SET 
                name = '12CM-264',
                name_bg = '12CM-264',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379967/Site_Pics/Decals/12cm/12cm-264.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379967/Site_Pics/Decals/12cm/12cm-264.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-264';
UPDATE products SET 
                name = '12CM-265',
                name_bg = '12CM-265',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-265.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-265.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-265';
UPDATE products SET 
                name = '12CM-266',
                name_bg = '12CM-266',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-266.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-266.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-266';
UPDATE products SET 
                name = '12CM-267',
                name_bg = '12CM-267',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-267.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379966/Site_Pics/Decals/12cm/12cm-267.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-267';
UPDATE products SET 
                name = '12CM-268',
                name_bg = '12CM-268',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-268.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-268.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-268';
UPDATE products SET 
                name = '12CM-269',
                name_bg = '12CM-269',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-269.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-269.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-269';
UPDATE products SET 
                name = '12CM-270',
                name_bg = '12CM-270',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-270.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-270.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-270';
UPDATE products SET 
                name = '12CM-271',
                name_bg = '12CM-271',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-271.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-271.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-271';
UPDATE products SET 
                name = '12CM-272',
                name_bg = '12CM-272',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-272.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-272.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-272';
UPDATE products SET 
                name = '12CM-273',
                name_bg = '12CM-273',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-273.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-273.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-273';
UPDATE products SET 
                name = '12CM-274',
                name_bg = '12CM-274',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-274.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-274.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-274';
UPDATE products SET 
                name = '12CM-275',
                name_bg = '12CM-275',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-275.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-275.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-275';
UPDATE products SET 
                name = '12CM-276',
                name_bg = '12CM-276',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-276.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379968/Site_Pics/Decals/12cm/12cm-276.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-276';
UPDATE products SET 
                name = '12CM-277',
                name_bg = '12CM-277',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380075/Site_Pics/Decals/12cm/12cm-277.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380075/Site_Pics/Decals/12cm/12cm-277.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-277';
UPDATE products SET 
                name = '12CM-278',
                name_bg = '12CM-278',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-278.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-278.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-278';
UPDATE products SET 
                name = '12CM-279',
                name_bg = '12CM-279',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-279.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-279.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-279';
UPDATE products SET 
                name = '12CM-280',
                name_bg = '12CM-280',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-280.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-280.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-280';
UPDATE products SET 
                name = '12CM-281',
                name_bg = '12CM-281',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-281.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-281.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-281';
UPDATE products SET 
                name = '12CM-282',
                name_bg = '12CM-282',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-282.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-282.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-282';
UPDATE products SET 
                name = '12CM-283',
                name_bg = '12CM-283',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-283.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-283.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-283';
UPDATE products SET 
                name = '12CM-284',
                name_bg = '12CM-284',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380075/Site_Pics/Decals/12cm/12cm-284.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380075/Site_Pics/Decals/12cm/12cm-284.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-284';
UPDATE products SET 
                name = '12CM-285',
                name_bg = '12CM-285',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-285.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380074/Site_Pics/Decals/12cm/12cm-285.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-285';
UPDATE products SET 
                name = '12CM-286',
                name_bg = '12CM-286',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-286.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-286.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-286';
UPDATE products SET 
                name = '12CM-287',
                name_bg = '12CM-287',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-287.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-287.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-287';
UPDATE products SET 
                name = '12CM-288',
                name_bg = '12CM-288',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380088/Site_Pics/Decals/12cm/12cm-288.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380088/Site_Pics/Decals/12cm/12cm-288.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-288';
UPDATE products SET 
                name = '12CM-289',
                name_bg = '12CM-289',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-289.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-289.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-289';
UPDATE products SET 
                name = '12CM-290',
                name_bg = '12CM-290',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380084/Site_Pics/Decals/12cm/12cm-290.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380084/Site_Pics/Decals/12cm/12cm-290.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-290';
UPDATE products SET 
                name = '12CM-291',
                name_bg = '12CM-291',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380089/Site_Pics/Decals/12cm/12cm-291.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380089/Site_Pics/Decals/12cm/12cm-291.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-291';
UPDATE products SET 
                name = '12CM-292',
                name_bg = '12CM-292',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-292.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-292.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-292';
UPDATE products SET 
                name = '12CM-293',
                name_bg = '12CM-293',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380091/Site_Pics/Decals/12cm/12cm-293.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380091/Site_Pics/Decals/12cm/12cm-293.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-293';
UPDATE products SET 
                name = '12CM-294',
                name_bg = '12CM-294',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-294.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380081/Site_Pics/Decals/12cm/12cm-294.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-294';
UPDATE products SET 
                name = '12CM-295',
                name_bg = '12CM-295',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380096/Site_Pics/Decals/12cm/12cm-295.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380096/Site_Pics/Decals/12cm/12cm-295.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-295';
UPDATE products SET 
                name = '12CM-296',
                name_bg = '12CM-296',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380096/Site_Pics/Decals/12cm/12cm-296.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380096/Site_Pics/Decals/12cm/12cm-296.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-296';
UPDATE products SET 
                name = '12CM-297',
                name_bg = '12CM-297',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380096/Site_Pics/Decals/12cm/12cm-297.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380096/Site_Pics/Decals/12cm/12cm-297.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-297';
UPDATE products SET 
                name = '12CM-298',
                name_bg = '12CM-298',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380100/Site_Pics/Decals/12cm/12cm-298.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380100/Site_Pics/Decals/12cm/12cm-298.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-298';
UPDATE products SET 
                name = '12CM-299',
                name_bg = '12CM-299',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-299.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-299.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-299';
UPDATE products SET 
                name = '12CM-300',
                name_bg = '12CM-300',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-300.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-300.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-300';
UPDATE products SET 
                name = '12CM-301',
                name_bg = '12CM-301',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-301.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-301.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-301';
