UPDATE products SET 
                name = '12CM-102',
                name_bg = '12CM-102',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379553/Site_Pics/Decals/12cm/12cm-102.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379553/Site_Pics/Decals/12cm/12cm-102.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-102';
UPDATE products SET 
                name = '12CM-103',
                name_bg = '12CM-103',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379554/Site_Pics/Decals/12cm/12cm-103.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379554/Site_Pics/Decals/12cm/12cm-103.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-103';
UPDATE products SET 
                name = '12CM-104',
                name_bg = '12CM-104',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379554/Site_Pics/Decals/12cm/12cm-104.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379554/Site_Pics/Decals/12cm/12cm-104.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-104';
UPDATE products SET 
                name = '12CM-105',
                name_bg = '12CM-105',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379555/Site_Pics/Decals/12cm/12cm-105.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379555/Site_Pics/Decals/12cm/12cm-105.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-105';
UPDATE products SET 
                name = '12CM-106',
                name_bg = '12CM-106',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379556/Site_Pics/Decals/12cm/12cm-106.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379556/Site_Pics/Decals/12cm/12cm-106.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-106';
UPDATE products SET 
                name = '12CM-107',
                name_bg = '12CM-107',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379557/Site_Pics/Decals/12cm/12cm-107.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379557/Site_Pics/Decals/12cm/12cm-107.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-107';
UPDATE products SET 
                name = '12CM-108',
                name_bg = '12CM-108',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379558/Site_Pics/Decals/12cm/12cm-108.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379558/Site_Pics/Decals/12cm/12cm-108.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-108';
UPDATE products SET 
                name = '12CM-109',
                name_bg = '12CM-109',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379559/Site_Pics/Decals/12cm/12cm-109.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379559/Site_Pics/Decals/12cm/12cm-109.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-109';
UPDATE products SET 
                name = '12CM-110',
                name_bg = '12CM-110',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379560/Site_Pics/Decals/12cm/12cm-110.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379560/Site_Pics/Decals/12cm/12cm-110.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-110';
UPDATE products SET 
                name = '12CM-111',
                name_bg = '12CM-111',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379564/Site_Pics/Decals/12cm/12cm-111.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379564/Site_Pics/Decals/12cm/12cm-111.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-111';
UPDATE products SET 
                name = '12CM-112',
                name_bg = '12CM-112',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379565/Site_Pics/Decals/12cm/12cm-112.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379565/Site_Pics/Decals/12cm/12cm-112.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-112';
UPDATE products SET 
                name = '12CM-113',
                name_bg = '12CM-113',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379566/Site_Pics/Decals/12cm/12cm-113.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379566/Site_Pics/Decals/12cm/12cm-113.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-113';
UPDATE products SET 
                name = '12CM-114',
                name_bg = '12CM-114',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379567/Site_Pics/Decals/12cm/12cm-114.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379567/Site_Pics/Decals/12cm/12cm-114.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-114';
UPDATE products SET 
                name = '12CM-115',
                name_bg = '12CM-115',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379568/Site_Pics/Decals/12cm/12cm-115.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379568/Site_Pics/Decals/12cm/12cm-115.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-115';
UPDATE products SET 
                name = '12CM-116',
                name_bg = '12CM-116',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379570/Site_Pics/Decals/12cm/12cm-116.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379570/Site_Pics/Decals/12cm/12cm-116.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-116';
UPDATE products SET 
                name = '12CM-117',
                name_bg = '12CM-117',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379571/Site_Pics/Decals/12cm/12cm-117.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379571/Site_Pics/Decals/12cm/12cm-117.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-117';
UPDATE products SET 
                name = '12CM-118',
                name_bg = '12CM-118',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379573/Site_Pics/Decals/12cm/12cm-118.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379573/Site_Pics/Decals/12cm/12cm-118.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-118';
UPDATE products SET 
                name = '12CM-119',
                name_bg = '12CM-119',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379578/Site_Pics/Decals/12cm/12cm-119.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379578/Site_Pics/Decals/12cm/12cm-119.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-119';
UPDATE products SET 
                name = '12CM-120',
                name_bg = '12CM-120',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379591/Site_Pics/Decals/12cm/12cm-120.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379591/Site_Pics/Decals/12cm/12cm-120.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-120';
UPDATE products SET 
                name = '12CM-121',
                name_bg = '12CM-121',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379596/Site_Pics/Decals/12cm/12cm-121.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379596/Site_Pics/Decals/12cm/12cm-121.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-121';
UPDATE products SET 
                name = '12CM-122',
                name_bg = '12CM-122',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379599/Site_Pics/Decals/12cm/12cm-122.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379599/Site_Pics/Decals/12cm/12cm-122.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-122';
UPDATE products SET 
                name = '12CM-123',
                name_bg = '12CM-123',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379612/Site_Pics/Decals/12cm/12cm-123.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379612/Site_Pics/Decals/12cm/12cm-123.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-123';
UPDATE products SET 
                name = '12CM-124',
                name_bg = '12CM-124',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379616/Site_Pics/Decals/12cm/12cm-124.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379616/Site_Pics/Decals/12cm/12cm-124.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-124';
UPDATE products SET 
                name = '12CM-125',
                name_bg = '12CM-125',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379617/Site_Pics/Decals/12cm/12cm-125.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379617/Site_Pics/Decals/12cm/12cm-125.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-125';
UPDATE products SET 
                name = '12CM-126',
                name_bg = '12CM-126',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379618/Site_Pics/Decals/12cm/12cm-126.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379618/Site_Pics/Decals/12cm/12cm-126.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-126';
UPDATE products SET 
                name = '12CM-127',
                name_bg = '12CM-127',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379619/Site_Pics/Decals/12cm/12cm-127.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379619/Site_Pics/Decals/12cm/12cm-127.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-127';
UPDATE products SET 
                name = '12CM-128',
                name_bg = '12CM-128',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379620/Site_Pics/Decals/12cm/12cm-128.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379620/Site_Pics/Decals/12cm/12cm-128.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-128';
UPDATE products SET 
                name = '12CM-129',
                name_bg = '12CM-129',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379621/Site_Pics/Decals/12cm/12cm-129.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379621/Site_Pics/Decals/12cm/12cm-129.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-129';
UPDATE products SET 
                name = '12CM-130',
                name_bg = '12CM-130',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379626/Site_Pics/Decals/12cm/12cm-130.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379626/Site_Pics/Decals/12cm/12cm-130.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-130';
UPDATE products SET 
                name = '12CM-131',
                name_bg = '12CM-131',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379627/Site_Pics/Decals/12cm/12cm-131.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379627/Site_Pics/Decals/12cm/12cm-131.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-131';
UPDATE products SET 
                name = '12CM-132',
                name_bg = '12CM-132',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379629/Site_Pics/Decals/12cm/12cm-132.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379629/Site_Pics/Decals/12cm/12cm-132.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-132';
UPDATE products SET 
                name = '12CM-133',
                name_bg = '12CM-133',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379631/Site_Pics/Decals/12cm/12cm-133.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379631/Site_Pics/Decals/12cm/12cm-133.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-133';
UPDATE products SET 
                name = '12CM-134',
                name_bg = '12CM-134',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379633/Site_Pics/Decals/12cm/12cm-134.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379633/Site_Pics/Decals/12cm/12cm-134.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-134';
UPDATE products SET 
                name = '12CM-135',
                name_bg = '12CM-135',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379634/Site_Pics/Decals/12cm/12cm-135.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379634/Site_Pics/Decals/12cm/12cm-135.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-135';
UPDATE products SET 
                name = '12CM-136',
                name_bg = '12CM-136',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379636/Site_Pics/Decals/12cm/12cm-136.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379636/Site_Pics/Decals/12cm/12cm-136.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-136';
UPDATE products SET 
                name = '12CM-137',
                name_bg = '12CM-137',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379637/Site_Pics/Decals/12cm/12cm-137.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379637/Site_Pics/Decals/12cm/12cm-137.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-137';
UPDATE products SET 
                name = '12CM-138',
                name_bg = '12CM-138',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379644/Site_Pics/Decals/12cm/12cm-138.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379644/Site_Pics/Decals/12cm/12cm-138.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-138';
UPDATE products SET 
                name = '12CM-139',
                name_bg = '12CM-139',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379646/Site_Pics/Decals/12cm/12cm-139.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379646/Site_Pics/Decals/12cm/12cm-139.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-139';
UPDATE products SET 
                name = '12CM-140',
                name_bg = '12CM-140',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379650/Site_Pics/Decals/12cm/12cm-140.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379650/Site_Pics/Decals/12cm/12cm-140.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-140';
UPDATE products SET 
                name = '12CM-141',
                name_bg = '12CM-141',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379651/Site_Pics/Decals/12cm/12cm-141.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379651/Site_Pics/Decals/12cm/12cm-141.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-141';
UPDATE products SET 
                name = '12CM-142',
                name_bg = '12CM-142',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379652/Site_Pics/Decals/12cm/12cm-142.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379652/Site_Pics/Decals/12cm/12cm-142.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-142';
UPDATE products SET 
                name = '12CM-143',
                name_bg = '12CM-143',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379655/Site_Pics/Decals/12cm/12cm-143.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379655/Site_Pics/Decals/12cm/12cm-143.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-143';
UPDATE products SET 
                name = '12CM-144',
                name_bg = '12CM-144',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379656/Site_Pics/Decals/12cm/12cm-144.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379656/Site_Pics/Decals/12cm/12cm-144.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-144';
UPDATE products SET 
                name = '12CM-145',
                name_bg = '12CM-145',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379660/Site_Pics/Decals/12cm/12cm-145.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379660/Site_Pics/Decals/12cm/12cm-145.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-145';
UPDATE products SET 
                name = '12CM-146',
                name_bg = '12CM-146',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379662/Site_Pics/Decals/12cm/12cm-146.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379662/Site_Pics/Decals/12cm/12cm-146.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-146';
UPDATE products SET 
                name = '12CM-147',
                name_bg = '12CM-147',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379663/Site_Pics/Decals/12cm/12cm-147.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379663/Site_Pics/Decals/12cm/12cm-147.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-147';
UPDATE products SET 
                name = '12CM-148',
                name_bg = '12CM-148',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379664/Site_Pics/Decals/12cm/12cm-148.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379664/Site_Pics/Decals/12cm/12cm-148.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-148';
UPDATE products SET 
                name = '12CM-149',
                name_bg = '12CM-149',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379667/Site_Pics/Decals/12cm/12cm-149.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379667/Site_Pics/Decals/12cm/12cm-149.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-149';
UPDATE products SET 
                name = '12CM-150',
                name_bg = '12CM-150',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379669/Site_Pics/Decals/12cm/12cm-150.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379669/Site_Pics/Decals/12cm/12cm-150.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-150';
UPDATE products SET 
                name = '12CM-151',
                name_bg = '12CM-151',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379670/Site_Pics/Decals/12cm/12cm-151.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379670/Site_Pics/Decals/12cm/12cm-151.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-151';
UPDATE products SET 
                name = '12CM-152',
                name_bg = '12CM-152',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379672/Site_Pics/Decals/12cm/12cm-152.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379672/Site_Pics/Decals/12cm/12cm-152.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-152';
UPDATE products SET 
                name = '12CM-153',
                name_bg = '12CM-153',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379673/Site_Pics/Decals/12cm/12cm-153.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379673/Site_Pics/Decals/12cm/12cm-153.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-153';
UPDATE products SET 
                name = '12CM-154',
                name_bg = '12CM-154',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379674/Site_Pics/Decals/12cm/12cm-154.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379674/Site_Pics/Decals/12cm/12cm-154.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-154';
UPDATE products SET 
                name = '12CM-155',
                name_bg = '12CM-155',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379675/Site_Pics/Decals/12cm/12cm-155.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379675/Site_Pics/Decals/12cm/12cm-155.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-155';
UPDATE products SET 
                name = '12CM-156',
                name_bg = '12CM-156',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379676/Site_Pics/Decals/12cm/12cm-156.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379676/Site_Pics/Decals/12cm/12cm-156.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-156';
UPDATE products SET 
                name = '12CM-157',
                name_bg = '12CM-157',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379677/Site_Pics/Decals/12cm/12cm-157.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379677/Site_Pics/Decals/12cm/12cm-157.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-157';
UPDATE products SET 
                name = '12CM-158',
                name_bg = '12CM-158',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379678/Site_Pics/Decals/12cm/12cm-158.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379678/Site_Pics/Decals/12cm/12cm-158.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-158';
UPDATE products SET 
                name = '12CM-159',
                name_bg = '12CM-159',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379680/Site_Pics/Decals/12cm/12cm-159.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379680/Site_Pics/Decals/12cm/12cm-159.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-159';
UPDATE products SET 
                name = '12CM-160',
                name_bg = '12CM-160',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379685/Site_Pics/Decals/12cm/12cm-160.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379685/Site_Pics/Decals/12cm/12cm-160.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-160';
UPDATE products SET 
                name = '12CM-161',
                name_bg = '12CM-161',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379686/Site_Pics/Decals/12cm/12cm-161.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379686/Site_Pics/Decals/12cm/12cm-161.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-161';
UPDATE products SET 
                name = '12CM-162',
                name_bg = '12CM-162',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379687/Site_Pics/Decals/12cm/12cm-162.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379687/Site_Pics/Decals/12cm/12cm-162.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-162';
UPDATE products SET 
                name = '12CM-163',
                name_bg = '12CM-163',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379689/Site_Pics/Decals/12cm/12cm-163.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379689/Site_Pics/Decals/12cm/12cm-163.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-163';
UPDATE products SET 
                name = '12CM-164',
                name_bg = '12CM-164',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379691/Site_Pics/Decals/12cm/12cm-164.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379691/Site_Pics/Decals/12cm/12cm-164.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-164';
UPDATE products SET 
                name = '12CM-165',
                name_bg = '12CM-165',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379692/Site_Pics/Decals/12cm/12cm-165.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379692/Site_Pics/Decals/12cm/12cm-165.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-165';
UPDATE products SET 
                name = '12CM-166',
                name_bg = '12CM-166',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379693/Site_Pics/Decals/12cm/12cm-166.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379693/Site_Pics/Decals/12cm/12cm-166.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-166';
UPDATE products SET 
                name = '12CM-167',
                name_bg = '12CM-167',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379694/Site_Pics/Decals/12cm/12cm-167.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379694/Site_Pics/Decals/12cm/12cm-167.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-167';
UPDATE products SET 
                name = '12CM-168',
                name_bg = '12CM-168',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379695/Site_Pics/Decals/12cm/12cm-168.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379695/Site_Pics/Decals/12cm/12cm-168.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-168';
UPDATE products SET 
                name = '12CM-169',
                name_bg = '12CM-169',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379696/Site_Pics/Decals/12cm/12cm-169.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379696/Site_Pics/Decals/12cm/12cm-169.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-169';
UPDATE products SET 
                name = '12CM-170',
                name_bg = '12CM-170',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379703/Site_Pics/Decals/12cm/12cm-170.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379703/Site_Pics/Decals/12cm/12cm-170.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-170';
UPDATE products SET 
                name = '12CM-171',
                name_bg = '12CM-171',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379704/Site_Pics/Decals/12cm/12cm-171.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379704/Site_Pics/Decals/12cm/12cm-171.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-171';
UPDATE products SET 
                name = '12CM-172',
                name_bg = '12CM-172',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379704/Site_Pics/Decals/12cm/12cm-172.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379704/Site_Pics/Decals/12cm/12cm-172.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-172';
UPDATE products SET 
                name = '12CM-173',
                name_bg = '12CM-173',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379706/Site_Pics/Decals/12cm/12cm-173.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379706/Site_Pics/Decals/12cm/12cm-173.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-173';
UPDATE products SET 
                name = '12CM-174',
                name_bg = '12CM-174',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379707/Site_Pics/Decals/12cm/12cm-174.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379707/Site_Pics/Decals/12cm/12cm-174.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-174';
UPDATE products SET 
                name = '12CM-175',
                name_bg = '12CM-175',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379708/Site_Pics/Decals/12cm/12cm-175.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379708/Site_Pics/Decals/12cm/12cm-175.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-175';
UPDATE products SET 
                name = '12CM-176',
                name_bg = '12CM-176',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379709/Site_Pics/Decals/12cm/12cm-176.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379709/Site_Pics/Decals/12cm/12cm-176.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-176';
UPDATE products SET 
                name = '12CM-177',
                name_bg = '12CM-177',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379710/Site_Pics/Decals/12cm/12cm-177.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379710/Site_Pics/Decals/12cm/12cm-177.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-177';
UPDATE products SET 
                name = '12CM-178',
                name_bg = '12CM-178',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-178.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-178.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-178';
UPDATE products SET 
                name = '12CM-179',
                name_bg = '12CM-179',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-179.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-179.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-179';
UPDATE products SET 
                name = '12CM-180',
                name_bg = '12CM-180',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-180.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-180.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-180';
UPDATE products SET 
                name = '12CM-181',
                name_bg = '12CM-181',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-181.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379918/Site_Pics/Decals/12cm/12cm-181.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-181';
UPDATE products SET 
                name = '12CM-182',
                name_bg = '12CM-182',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-182.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-182.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-182';
UPDATE products SET 
                name = '12CM-183',
                name_bg = '12CM-183',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-183.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-183.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-183';
UPDATE products SET 
                name = '12CM-184',
                name_bg = '12CM-184',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-184.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-184.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-184';
UPDATE products SET 
                name = '12CM-185',
                name_bg = '12CM-185',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-185.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379919/Site_Pics/Decals/12cm/12cm-185.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-185';
UPDATE products SET 
                name = '12CM-186',
                name_bg = '12CM-186',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-186.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-186.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-186';
UPDATE products SET 
                name = '12CM-187',
                name_bg = '12CM-187',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-187.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-187.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-187';
UPDATE products SET 
                name = '12CM-188',
                name_bg = '12CM-188',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379925/Site_Pics/Decals/12cm/12cm-188.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379925/Site_Pics/Decals/12cm/12cm-188.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-188';
UPDATE products SET 
                name = '12CM-189',
                name_bg = '12CM-189',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-189.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-189.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-189';
UPDATE products SET 
                name = '12CM-190',
                name_bg = '12CM-190',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-190.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-190.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-190';
UPDATE products SET 
                name = '12CM-191',
                name_bg = '12CM-191',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-191.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-191.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-191';
UPDATE products SET 
                name = '12CM-192',
                name_bg = '12CM-192',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379925/Site_Pics/Decals/12cm/12cm-192.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379925/Site_Pics/Decals/12cm/12cm-192.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-192';
UPDATE products SET 
                name = '12CM-193',
                name_bg = '12CM-193',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379933/Site_Pics/Decals/12cm/12cm-193.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379933/Site_Pics/Decals/12cm/12cm-193.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-193';
UPDATE products SET 
                name = '12CM-194',
                name_bg = '12CM-194',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-194.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379926/Site_Pics/Decals/12cm/12cm-194.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-194';
UPDATE products SET 
                name = '12CM-195',
                name_bg = '12CM-195',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379934/Site_Pics/Decals/12cm/12cm-195.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379934/Site_Pics/Decals/12cm/12cm-195.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-195';
UPDATE products SET 
                name = '12CM-196',
                name_bg = '12CM-196',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379935/Site_Pics/Decals/12cm/12cm-196.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379935/Site_Pics/Decals/12cm/12cm-196.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-196';
UPDATE products SET 
                name = '12CM-197',
                name_bg = '12CM-197',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379938/Site_Pics/Decals/12cm/12cm-197.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379938/Site_Pics/Decals/12cm/12cm-197.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-197';
UPDATE products SET 
                name = '12CM-198',
                name_bg = '12CM-198',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379935/Site_Pics/Decals/12cm/12cm-198.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379935/Site_Pics/Decals/12cm/12cm-198.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-198';
UPDATE products SET 
                name = '12CM-199',
                name_bg = '12CM-199',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379937/Site_Pics/Decals/12cm/12cm-199.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379937/Site_Pics/Decals/12cm/12cm-199.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-199';
UPDATE products SET 
                name = '12CM-200',
                name_bg = '12CM-200',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379936/Site_Pics/Decals/12cm/12cm-200.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379936/Site_Pics/Decals/12cm/12cm-200.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-200';
UPDATE products SET 
                name = '12CM-201',
                name_bg = '12CM-201',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379936/Site_Pics/Decals/12cm/12cm-201.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772379936/Site_Pics/Decals/12cm/12cm-201.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-201';
