UPDATE products SET 
                name = '12CM-302',
                name_bg = '12CM-302',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-302.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380099/Site_Pics/Decals/12cm/12cm-302.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-302';
UPDATE products SET 
                name = '12CM-303',
                name_bg = '12CM-303',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380102/Site_Pics/Decals/12cm/12cm-303.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380102/Site_Pics/Decals/12cm/12cm-303.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-303';
UPDATE products SET 
                name = '12CM-304',
                name_bg = '12CM-304',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380105/Site_Pics/Decals/12cm/12cm-304.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380105/Site_Pics/Decals/12cm/12cm-304.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-304';
UPDATE products SET 
                name = '12CM-305',
                name_bg = '12CM-305',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380105/Site_Pics/Decals/12cm/12cm-305.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380105/Site_Pics/Decals/12cm/12cm-305.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-305';
UPDATE products SET 
                name = '12CM-306',
                name_bg = '12CM-306',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380111/Site_Pics/Decals/12cm/12cm-306.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380111/Site_Pics/Decals/12cm/12cm-306.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-306';
UPDATE products SET 
                name = '12CM-307',
                name_bg = '12CM-307',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380106/Site_Pics/Decals/12cm/12cm-307.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380106/Site_Pics/Decals/12cm/12cm-307.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-307';
UPDATE products SET 
                name = '12CM-308',
                name_bg = '12CM-308',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380106/Site_Pics/Decals/12cm/12cm-308.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380106/Site_Pics/Decals/12cm/12cm-308.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-308';
UPDATE products SET 
                name = '12CM-309',
                name_bg = '12CM-309',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380106/Site_Pics/Decals/12cm/12cm-309.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380106/Site_Pics/Decals/12cm/12cm-309.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-309';
UPDATE products SET 
                name = '12CM-310',
                name_bg = '12CM-310',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380109/Site_Pics/Decals/12cm/12cm-310.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380109/Site_Pics/Decals/12cm/12cm-310.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-310';
UPDATE products SET 
                name = '12CM-311',
                name_bg = '12CM-311',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380110/Site_Pics/Decals/12cm/12cm-311.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380110/Site_Pics/Decals/12cm/12cm-311.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-311';
UPDATE products SET 
                name = '12CM-312',
                name_bg = '12CM-312',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380110/Site_Pics/Decals/12cm/12cm-312.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380110/Site_Pics/Decals/12cm/12cm-312.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-312';
UPDATE products SET 
                name = '12CM-313',
                name_bg = '12CM-313',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-313.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-313.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-313';
UPDATE products SET 
                name = '12CM-314',
                name_bg = '12CM-314',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-314.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-314.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-314';
UPDATE products SET 
                name = '12CM-315',
                name_bg = '12CM-315',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-315.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-315.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-315';
UPDATE products SET 
                name = '12CM-316',
                name_bg = '12CM-316',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-316.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-316.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-316';
UPDATE products SET 
                name = '12CM-317',
                name_bg = '12CM-317',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-317.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-317.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-317';
UPDATE products SET 
                name = '12CM-318',
                name_bg = '12CM-318',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-318.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-318.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-318';
UPDATE products SET 
                name = '12CM-319',
                name_bg = '12CM-319',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380111/Site_Pics/Decals/12cm/12cm-319.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380111/Site_Pics/Decals/12cm/12cm-319.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-319';
UPDATE products SET 
                name = '12CM-320',
                name_bg = '12CM-320',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-320.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-320.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-320';
UPDATE products SET 
                name = '12CM-321',
                name_bg = '12CM-321',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-321.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380112/Site_Pics/Decals/12cm/12cm-321.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-321';
UPDATE products SET 
                name = '12CM-322',
                name_bg = '12CM-322',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-322.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-322.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-322';
UPDATE products SET 
                name = '12CM-323',
                name_bg = '12CM-323',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-323.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-323.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-323';
UPDATE products SET 
                name = '12CM-324',
                name_bg = '12CM-324',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-324.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-324.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-324';
UPDATE products SET 
                name = '12CM-325',
                name_bg = '12CM-325',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-325.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-325.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-325';
UPDATE products SET 
                name = '12CM-326',
                name_bg = '12CM-326',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-326.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-326.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-326';
UPDATE products SET 
                name = '12CM-327',
                name_bg = '12CM-327',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-327.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-327.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-327';
UPDATE products SET 
                name = '12CM-328',
                name_bg = '12CM-328',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-328.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380114/Site_Pics/Decals/12cm/12cm-328.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-328';
UPDATE products SET 
                name = '12CM-329',
                name_bg = '12CM-329',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-329.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-329.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-329';
UPDATE products SET 
                name = '12CM-330',
                name_bg = '12CM-330',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-330.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380113/Site_Pics/Decals/12cm/12cm-330.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-330';
UPDATE products SET 
                name = '12CM-331',
                name_bg = '12CM-331',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380116/Site_Pics/Decals/12cm/12cm-331.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380116/Site_Pics/Decals/12cm/12cm-331.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-331';
UPDATE products SET 
                name = '12CM-332',
                name_bg = '12CM-332',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-332.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-332.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-332';
UPDATE products SET 
                name = '12CM-333',
                name_bg = '12CM-333',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-333.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-333.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-333';
UPDATE products SET 
                name = '12CM-334',
                name_bg = '12CM-334',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-334.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-334.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-334';
UPDATE products SET 
                name = '12CM-335',
                name_bg = '12CM-335',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-335.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-335.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-335';
UPDATE products SET 
                name = '12CM-336',
                name_bg = '12CM-336',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-336.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-336.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-336';
UPDATE products SET 
                name = '12CM-337',
                name_bg = '12CM-337',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-337.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-337.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-337';
UPDATE products SET 
                name = '12CM-338',
                name_bg = '12CM-338',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-338.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-338.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-338';
UPDATE products SET 
                name = '12CM-339',
                name_bg = '12CM-339',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-339.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380115/Site_Pics/Decals/12cm/12cm-339.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-339';
UPDATE products SET 
                name = '12CM-340',
                name_bg = '12CM-340',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-340.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-340.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-340';
UPDATE products SET 
                name = '12CM-341',
                name_bg = '12CM-341',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-341.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-341.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-341';
UPDATE products SET 
                name = '12CM-342',
                name_bg = '12CM-342',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-342.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-342.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-342';
UPDATE products SET 
                name = '12CM-343',
                name_bg = '12CM-343',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-343.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-343.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-343';
UPDATE products SET 
                name = '12CM-344',
                name_bg = '12CM-344',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-344.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-344.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-344';
UPDATE products SET 
                name = '12CM-345',
                name_bg = '12CM-345',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-345.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-345.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-345';
UPDATE products SET 
                name = '12CM-346',
                name_bg = '12CM-346',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-346.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-346.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-346';
UPDATE products SET 
                name = '12CM-347',
                name_bg = '12CM-347',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-347.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-347.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-347';
UPDATE products SET 
                name = '12CM-348',
                name_bg = '12CM-348',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-348.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380124/Site_Pics/Decals/12cm/12cm-348.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-348';
UPDATE products SET 
                name = '12CM-349',
                name_bg = '12CM-349',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380125/Site_Pics/Decals/12cm/12cm-349.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380125/Site_Pics/Decals/12cm/12cm-349.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-349';
UPDATE products SET 
                name = '12CM-350',
                name_bg = '12CM-350',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380128/Site_Pics/Decals/12cm/12cm-350.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380128/Site_Pics/Decals/12cm/12cm-350.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-350';
UPDATE products SET 
                name = '12CM-351',
                name_bg = '12CM-351',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-351.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-351.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-351';
UPDATE products SET 
                name = '12CM-352',
                name_bg = '12CM-352',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380126/Site_Pics/Decals/12cm/12cm-352.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380126/Site_Pics/Decals/12cm/12cm-352.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-352';
UPDATE products SET 
                name = '12CM-353',
                name_bg = '12CM-353',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-353.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-353.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-353';
UPDATE products SET 
                name = '12CM-354',
                name_bg = '12CM-354',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-354.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-354.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-354';
UPDATE products SET 
                name = '12CM-355',
                name_bg = '12CM-355',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-355.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-355.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-355';
UPDATE products SET 
                name = '12CM-356',
                name_bg = '12CM-356',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-356.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-356.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-356';
UPDATE products SET 
                name = '12CM-357',
                name_bg = '12CM-357',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380126/Site_Pics/Decals/12cm/12cm-357.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380126/Site_Pics/Decals/12cm/12cm-357.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-357';
UPDATE products SET 
                name = '12CM-358',
                name_bg = '12CM-358',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-358.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380127/Site_Pics/Decals/12cm/12cm-358.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-358';
UPDATE products SET 
                name = '12CM-359',
                name_bg = '12CM-359',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-359.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-359.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-359';
UPDATE products SET 
                name = '12CM-360',
                name_bg = '12CM-360',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-360.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-360.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-360';
UPDATE products SET 
                name = '12CM-361',
                name_bg = '12CM-361',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-361.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-361.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-361';
UPDATE products SET 
                name = '12CM-362',
                name_bg = '12CM-362',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-362.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-362.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-362';
UPDATE products SET 
                name = '12CM-363',
                name_bg = '12CM-363',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-363.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-363.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-363';
UPDATE products SET 
                name = '12CM-364',
                name_bg = '12CM-364',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380130/Site_Pics/Decals/12cm/12cm-364.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380130/Site_Pics/Decals/12cm/12cm-364.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-364';
UPDATE products SET 
                name = '12CM-365',
                name_bg = '12CM-365',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-365.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-365.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-365';
UPDATE products SET 
                name = '12CM-366',
                name_bg = '12CM-366',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-366.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-366.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-366';
UPDATE products SET 
                name = '12CM-367',
                name_bg = '12CM-367',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-367.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380129/Site_Pics/Decals/12cm/12cm-367.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-367';
UPDATE products SET 
                name = '12CM-368',
                name_bg = '12CM-368',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380201/Site_Pics/Decals/12cm/12cm-368.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380201/Site_Pics/Decals/12cm/12cm-368.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-368';
UPDATE products SET 
                name = '12CM-369',
                name_bg = '12CM-369',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380203/Site_Pics/Decals/12cm/12cm-369.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380203/Site_Pics/Decals/12cm/12cm-369.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-369';
UPDATE products SET 
                name = '12CM-370',
                name_bg = '12CM-370',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380205/Site_Pics/Decals/12cm/12cm-370.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380205/Site_Pics/Decals/12cm/12cm-370.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-370';
UPDATE products SET 
                name = '12CM-371',
                name_bg = '12CM-371',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380206/Site_Pics/Decals/12cm/12cm-371.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380206/Site_Pics/Decals/12cm/12cm-371.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-371';
UPDATE products SET 
                name = '12CM-372',
                name_bg = '12CM-372',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380202/Site_Pics/Decals/12cm/12cm-372.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380202/Site_Pics/Decals/12cm/12cm-372.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-372';
UPDATE products SET 
                name = '12CM-373',
                name_bg = '12CM-373',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380197/Site_Pics/Decals/12cm/12cm-373.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380197/Site_Pics/Decals/12cm/12cm-373.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-373';
UPDATE products SET 
                name = '12CM-374',
                name_bg = '12CM-374',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380201/Site_Pics/Decals/12cm/12cm-374.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380201/Site_Pics/Decals/12cm/12cm-374.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-374';
UPDATE products SET 
                name = '12CM-375',
                name_bg = '12CM-375',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380206/Site_Pics/Decals/12cm/12cm-375.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380206/Site_Pics/Decals/12cm/12cm-375.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-375';
UPDATE products SET 
                name = '12CM-376',
                name_bg = '12CM-376',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380203/Site_Pics/Decals/12cm/12cm-376.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380203/Site_Pics/Decals/12cm/12cm-376.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-376';
UPDATE products SET 
                name = '12CM-377',
                name_bg = '12CM-377',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-377.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-377.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-377';
UPDATE products SET 
                name = '12CM-378',
                name_bg = '12CM-378',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-378.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-378.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-378';
UPDATE products SET 
                name = '12CM-379',
                name_bg = '12CM-379',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-379.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-379.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-379';
UPDATE products SET 
                name = '12CM-380',
                name_bg = '12CM-380',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-380.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-380.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-380';
UPDATE products SET 
                name = '12CM-381',
                name_bg = '12CM-381',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380208/Site_Pics/Decals/12cm/12cm-381.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380208/Site_Pics/Decals/12cm/12cm-381.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-381';
UPDATE products SET 
                name = '12CM-382',
                name_bg = '12CM-382',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-382.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-382.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-382';
UPDATE products SET 
                name = '12CM-383',
                name_bg = '12CM-383',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-383.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380207/Site_Pics/Decals/12cm/12cm-383.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-383';
UPDATE products SET 
                name = '12CM-384',
                name_bg = '12CM-384',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380208/Site_Pics/Decals/12cm/12cm-384.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380208/Site_Pics/Decals/12cm/12cm-384.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-384';
UPDATE products SET 
                name = '12CM-385',
                name_bg = '12CM-385',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380208/Site_Pics/Decals/12cm/12cm-385.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380208/Site_Pics/Decals/12cm/12cm-385.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-385';
UPDATE products SET 
                name = '12CM-386',
                name_bg = '12CM-386',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-386.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-386.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-386';
UPDATE products SET 
                name = '12CM-387',
                name_bg = '12CM-387',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-387.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-387.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-387';
UPDATE products SET 
                name = '12CM-388',
                name_bg = '12CM-388',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-388.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-388.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-388';
UPDATE products SET 
                name = '12CM-389',
                name_bg = '12CM-389',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-389.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-389.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-389';
UPDATE products SET 
                name = '12CM-390',
                name_bg = '12CM-390',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-390.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-390.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-390';
UPDATE products SET 
                name = '12CM-391',
                name_bg = '12CM-391',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-391.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-391.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-391';
UPDATE products SET 
                name = '12CM-392',
                name_bg = '12CM-392',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-392.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380211/Site_Pics/Decals/12cm/12cm-392.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-392';
UPDATE products SET 
                name = '12CM-393',
                name_bg = '12CM-393',
                avatar = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-393.jpg',
                cover_image = 'https://res.cloudinary.com/die68h4oh/image/upload/v1772380210/Site_Pics/Decals/12cm/12cm-393.jpg',
                categories = '["12cm","Стикери"]',
                description = 'Висококачествен винилов стикер от CarDecal.',
                price_eur = 0.5,
                card_images = '[]',
                updated_at = NOW()
                WHERE slug = '12cm-393';
